//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCNorthwind_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_log
    {
        public int LogID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string UserName { get; set; }
    }
}
